version: '2'

services:
  main:
    container_name: ubuntu
    build: .
    restart: unless-stopped
    cap_add:
      - ALL
    ports:
      - "20022:22"
    environment:
      - EDITOR=vim
    volumes:
      - /home/thong/Documents/project/advanced-unix-programming/:/home
    privileged: true
    networks:
        default:
        internal:

networks:
    default:
    internal:
        internal: true
